### ISSUE TITLE
[Localization] Hardcoded Translation Strings.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [Lucaslah/WeatherChanger#4]
Hello!

I found that this Mod has Strings that are hardcoded and can't be translated into other Languages...

There's Screenshots and Links to the .java Files with that Strings.
[`WeatherChanger.java`](https://github.com/Lucaslah/WeatherChanger/blob/main/common/src/main/java/me/lucaslah/weatherchanger/WeatherChanger.java)
[`keys/*.java and WeatherChangerCommand.java`](https://imgur.com/a/uy2zdYP)

**Comment by Lucaslah** [comment]
Hi, thanks for letting me know, Ill fix this as soon as possible.

**Comment by Lucaslah** [comment]
@Amirhan-Taipovjan-Greatest-I I have opened a PR that should fix this issue, could you please confirm that it fixes everything you would like?

You can download the development build here: https://github.com/Lucaslah/WeatherChanger/actions/runs/8874717930 (download the `weather-changer-build` artifact and extract, forge and fabric builds are included.

Also feel free to submit PRs for translations.

Thanks

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> @Amirhan-Taipovjan-Greatest-I I have opened a PR that should fix this issue, could you please confirm that it fixes everything you would like?
> 
> Also feel free to submit PRs for translations.
> 
> Thanks

All `commands.weatherchanger.set.*` Strings can't be used... I still see English Fallback even if I added translations.
![image](https://github.com/Lucaslah/WeatherChanger/assets/51203385/edef5bfe-e758-4fa4-8b34-a1293b76b2a8)
![image](https://github.com/Lucaslah/WeatherChanger/assets/51203385/593a699c-6b97-4787-bbdd-fd6b092e7047)
![image](https://github.com/Lucaslah/WeatherChanger/assets/51203385/44697281-62e0-41a0-8c6c-6b8897952735)
![image](https://github.com/Lucaslah/WeatherChanger/assets/51203385/14f5f111-9f36-454c-b573-20fe2486eedc)
![image](https://github.com/Lucaslah/WeatherChanger/assets/51203385/051cd6ab-9aa9-4c60-a960-f5675ce08e07)
![image](https://github.com/Lucaslah/WeatherChanger/assets/51203385/f6232989-45ff-4ecf-9b2f-52086c1b3b2e)
![image](https://github.com/Lucaslah/WeatherChanger/assets/51203385/00c111c4-d849-4588-a420-121254e56142)

**Comment by Lucaslah** [comment]
Should be fixed by https://github.com/Lucaslah/WeatherChanger/commit/4c046a38288c91dec7147a2a0fb48d186f668993

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> @Amirhan-Taipovjan-Greatest-I Should be fixed by [4c046a3](https://github.com/Lucaslah/WeatherChanger/commit/4c046a38288c91dec7147a2a0fb48d186f668993)

Yes, this Issue can be closed by that Commit...

**Comment by Lucaslah** [comment]
Great! Will publish this as soon as possible.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Great! Will publish this as soon as possible.

Thank You! I also found someone who also wants to use this Mod, so I would be nice if new version will be published =)

**Comment by Lucaslah** [comment]
Published version 1.0.1 🎉 

## Get the release
- Modrinth: https://modrinth.com/mod/weather-changer
- Curseforge (once approved): https://www.curseforge.com/minecraft/mc-mods/weather-changer
- GitHub Releases: https://github.com/Lucaslah/WeatherChanger/releases/tag/1.0.1
